# 一维数组

In [1]:
import numpy as np
list1 = [1,2,3,4]
oneArray = np.array(list1)
print(type(oneArray))
print(oneArray)
# 创建数组的多种形式
# 1. 直接传入列表的方式
t1 = np.array([1,2,3])
print(t1)
print(type(t1))
'''
[1 2 3]
<class 'numpy.ndarray'>
'''
# 2. 传入range生成序列
t2 = np.array(range(10))
print(t2)
print(type(t2))
'''
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
'''
# 3. 使用numpy自带的np.arange()生成数组
t3 = np.arange(0,10,2)
print(t3)
print(type(t3))
'''
[0 2 4 6 8]
<class 'numpy.ndarray'>
'''

<class 'numpy.ndarray'>
[1 2 3 4]
[1 2 3]
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[0 2 4 6 8]
<class 'numpy.ndarray'>


"\n[0 2 4 6 8]\n<class 'numpy.ndarray'>\n"

# ndarray与Python原生list运算效率对比

In [2]:
import random
import time
import numpy as np
a = []
for i in range(100000000):
    a.append(random.random())
t1 = time.time()
sum1 = sum(a)
t2 = time.time()
b = np.array(a)
t4 = time.time()
sum3 = np.sum(b)
t5 = time.time()
print(t2 - t1, t5 - t4)

0.454423189163208 0.057213544845581055


# 创建二维数组

In [3]:
import numpy as np
list2 = [[1,2],[3,4],[5,6]]
twoArray = np.array(list2)
print(twoArray)

[[1 2]
 [3 4]
 [5 6]]


# 常用属性

In [4]:
list2 = [[1,2],[3,4],[5,6]]
twoArray = np.array(list2)
# 获取数组的维度( 注意： 与函数的参数很像)
print(twoArray.ndim)
# 形状（行，列）
print(twoArray.shape)
# 有多少个元素
print(twoArray.size)

2
(3, 2)
6


# 调整数组的形状

In [5]:
four = np.array([[1,2,3],[4,5,6]])
# 修改的是原有的
four.shape = (3,2)
print(four)
# 返回一个新的数组
four = four.reshape(3,2)
print(four)
# 将多维变成一维数组
five = four.reshape((6,),order='F')
# 默认情况下‘C’以行为主的顺序展开，‘F’（Fortran风格）意味着以列的顺序展开
six = four.flatten(order='F')
print(five)
print(six)
# 拓展：数组的形状
t = np.arange(24)
print(t)
print(t.shape)
# 转换成二维
t1 = t.reshape((4,6))
print(t1)
print(t1.shape)

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[1 3 5 2 4 6]
[1 3 5 2 4 6]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)


# Numpy的数据类型

In [6]:
import random
# 返回数组中每个元素的字节单位长度，dtype设置数据类型
f = np.array([1,2,3,4,5], dtype = np.int16)
print(f.itemsize) # 1 np.int8(一个字节)
# 获取数据类型
print(f.dtype)
# 调整数据类型
f1 = f.astype(np.int64)
print(f1.dtype)
# 拓展随机生成小数
# 使用python语法，保留两位
print(round(random.random(),2))
arr = np.array([random.random() for i in range(10)])
# 取小数点后两位
print(np.round(arr,2))

2
int16
int64
0.81
[0.34 0.42 0.84 0.11 0.6  0.49 0.59 0.14 0.86 0.73]


# 数组和数的计算

In [7]:
# 由于numpy的广播机制，在运算过程中，加减乘除的值被广播到所有的元素上面
t1 =np.arange(24).reshape((6,4))
print(t1+2)
print("-"*20)
print(t1*2)
print("-"*20)
print(t1/2)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
--------------------
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]
--------------------
[[ 0.   0.5  1.   1.5]
 [ 2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5]
 [10.  10.5 11.  11.5]]


# 数组与数组之间的操作

In [8]:
# 同种形状的数组(对应位置进行计算操作)
t1 = np.arange(24).reshape((6,4))
t2 = np.arange(100,124).reshape((6,4))
print(t1+t2)
print(t1*t2)
# 不同形状的多维数组不能计算
# t1 = np.arange(24).reshape((4,6))
# t2 = np.arange(18).reshape((3,6))
# print(t1)
# print(t2)
# print(t1-t2)
'''
ValueError: operands could not be broadcast together with shapes (4,6) (3,6)
'''

[[100 102 104 106]
 [108 110 112 114]
 [116 118 120 122]
 [124 126 128 130]
 [132 134 136 138]
 [140 142 144 146]]
[[   0  101  204  309]
 [ 416  525  636  749]
 [ 864  981 1100 1221]
 [1344 1469 1596 1725]
 [1856 1989 2124 2261]
 [2400 2541 2684 2829]]


'\nValueError: operands could not be broadcast together with shapes (4,6) (3,6)\n'

## 行数或者列数相同的一维数组和多维数组可以进行计算：
行形状相同(会与每一行数组的对应位相操作)

In [9]:
t1 = np.arange(24).reshape((4,6))
t2 = np.arange(0,6)
print(t1-t2)

[[ 0  0  0  0  0  0]
 [ 6  6  6  6  6  6]
 [12 12 12 12 12 12]
 [18 18 18 18 18 18]]


列形状相同(会与每一个相同维度的数组的对应位相操作)

In [10]:
t1 = np.arange(24).reshape((4,6))
t2 = np.arange(4).reshape((4,1))
print(t1-t2)

[[ 0  1  2  3  4  5]
 [ 5  6  7  8  9 10]
 [10 11 12 13 14 15]
 [15 16 17 18 19 20]]


# 数组中的轴

In [11]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(np.sum(a,axis=0)) # [5 7 9]
print(np.sum(a,axis = 1)) # [ 6 15]
print(np.sum(a))
a=np.arange(27).reshape((3,3,3))
print(a)
b=np.sum(a, axis=0)
print("-"*20)
print(b)
c=np.sum(a, axis=1)
print("-"*20)
print(c)
d=np.sum(a, axis=2)
print("-"*20)
print(d)
# 总结： 在计算的时候可以想象成是每一个坐标轴，分别计算这个轴上面的每一个刻度上的值，或者在二维数组中记住0表示列1表示行

[5 7 9]
[ 6 15]
21
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
--------------------
[[27 30 33]
 [36 39 42]
 [45 48 51]]
--------------------
[[ 9 12 15]
 [36 39 42]
 [63 66 69]]
--------------------
[[ 3 12 21]
 [30 39 48]
 [57 66 75]]


In [12]:
a = np.arange(24).reshape((2,3,4))
b = np.sum(a, axis=0)
print('-' * 20) 
print(b.shape)
c = np.sum(a, axis=1)
print('-' * 20) 
print(c.shape)
d = np.sum(a, axis=2)
print('-' * 20) 
print(d.shape)

--------------------
(3, 4)
--------------------
(2, 4)
--------------------
(2, 3)


# 索引和切片

In [13]:
import numpy as np

a = np.arange(10)
# 冒号分割切片参数start:stop:step来进行操作print(a[2:8:2]) # 从索引2到索引8，每隔2个取一个

# 如果只放置一个参数，如[2]，将返回与该索引相对应的单个元素
print(a[2],a)

# 如果为[2:]，表示从该索引开始以后的所有项都将被提取
print(a[2:])

print(a[2:8:2]) # 切片是左闭右开

2 [0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2 4 6]


In [14]:
# 多维数组的操作方法
import numpy as np
t1 = np.arange(24).reshape(4,6)
print(t1)
print('*'*20)
print(t1[1]) # 取一行(一行代表是一条数据，索引也是从0开始的) print(t1[1,:]) # 取一行
print('*'*20)
print(t1[1:])# 取连续的多行
print('*'*20)
print(t1[1:3,:])# 取连续的多行
print('*'*20)
print(t1[[0,2,3]])# 取不连续的多行
print('*'*20)
print(t1[[0,2,3],:])# 取不连续的多行
print('*'*20)
print(t1[:,1])# 取一列
print('*'*20)
print(t1[:,1:])# 连续的多列
print('*'*20)
print(t1[:,[0,2,3]])# 取不连续的多列
print('*'*20)
print(t1[2,3])# # 取某一个值,三行四列
print('*'*20)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[ 6  7  8  9 10 11]
********************
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
********************
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[ 1  7 13 19]
********************
[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [13 14 15 16 17]
 [19 20 21 22 23]]
********************
[[ 0  2  3]
 [ 6  8  9]
 [12 14 15]
 [18 20 21]]
********************
15
********************


# 数组中的数值修改

In [15]:
import numpy as np
t = np.arange( 24 ).reshape( 4, 6 )
# # 修改某一行的值
t[1, :] = 0
# # 修改某一列的值
t[:, 1] = 0
#
# # 修改连续多行
t[1:3, :] = 0#
# # 修改连续多列
t[:, 1:4] = 0#
# # 修改多行多列，取第二行到第四行，第三列到第五列
# t[1:4,2:5]=0
#
# # 修改多个不相邻的点
# t[[0,1],[0,3]]=0
# print(t)
# 可以根据条件修改，比如讲小于 10 的值改掉
t[t < 10] = 0# print(t)
# 使用逻辑判断
# np.logical_and & # np.logical_or |
# np.logical_not ~
t[(t > 2) & (t < 6)] = 0
# 与
t[(t < 2) | (t > 6)] = 0
# 或
t[~(t > 6)] = 0
# 非
# print(t)
t=t.clip(10,18)
print(t)
# # 拓 展
# # 三目运算（ np.where(condition, x, y)满足条件(condition)，输出 x，不满足输出y。)）
score = np.array( [[80, 88], [82, 81], [75, 81]] )
result = np.where( score > 80, True, False )
print( result )

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]
[[False  True]
 [ True  True]
 [False  True]]


# 数组的添加、删除和去重

## 数组的添加

In [16]:
# 1. numpy.append 函数在数组的末尾添加值。 追加操作会分配整个数组，并把原来的数组复制到新数组中。
# 此外，输入数组的维度必须匹配否则将生成 ValueError。
'''
参 数 说 明 ：
arr： 输 入 数 组
values：要向 arr 添加的值，需要和 arr 形状相同（除了要添加的轴）
axis：默认为 None。当 axis 无定义时，是横向加成，返回总是为一维数组！当 axis 有定义的
时候，分别为 0 和 1 的时候。当
axis 有定义的时候，分别为 0 和 1 的时候（列数要相同）。当 axis 为 1 时，数组是加在右边
（行数要相同）。
'''
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print('第一个数组：')
print(a)
print('\n')
print(' 向 数 组 添 加 元 素 ：')
print(np.append(a, [7, 8, 9]))
print('\n')
print('沿轴 0 添加元素：')
print(np.append(a, [[7, 8, 9]], axis=0))
print('\n')
print('沿轴 1 添加元素：')
print(np.append(a, [[5, 5, 5], [7, 8, 9]], axis=1))
# 2. numpy.insert
# 函数在给定索引之前，沿给定轴在输入数组中插入值。# 如果值的类型转换为要插入，则它与输入数组不同。
# 插入没有原地的，函数会返回一个新数组。 此外，如果未提供轴，则输入数组会被展开。
a = np.array([[1, 2], [3, 4], [5, 6]])
print('第一个数组：')
print(a)
print('\n')
print('未传递 Axis 参数。 在插入之前输入数组会被展开。')
print(np.insert(a, 3, [11, 12]))
print('\n')
print('传递了 Axis 参数。 会广播值数组来配输入数组。')
print('沿轴 0 广播：')
print(np.insert(a, 1, [11], axis=0))
print('\n')
print('沿轴 1 广播：')
print(np.insert(a, 1, 11, axis=1))

第一个数组：
[[1 2 3]
 [4 5 6]]


 向 数 组 添 加 元 素 ：
[1 2 3 4 5 6 7 8 9]


沿轴 0 添加元素：
[[1 2 3]
 [4 5 6]
 [7 8 9]]


沿轴 1 添加元素：
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]
第一个数组：
[[1 2]
 [3 4]
 [5 6]]


未传递 Axis 参数。 在插入之前输入数组会被展开。
[ 1  2  3 11 12  4  5  6]


传递了 Axis 参数。 会广播值数组来配输入数组。
沿轴 0 广播：
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]


沿轴 1 广播：
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


## 数组中的删除

In [17]:
#numpy.delete 函数返回从输入数组中删除指定子数组的新数组。 与 insert() 函数的情况一样，
# 如果未提供轴参数， 则输入数组将展开。
'''
参 数 说 明 ： arr： 输 入 数 组
obj：可以被切片，整数或者整数数组，表明要从输入数组删除的子数组 axis：
沿着它删除给定子数组的轴，如果未提供，则输入数组会被展开'''
import numpy as np
a = np.arange(12).reshape(3,4)
print('第一个数组：')
print(a)
print('\n')
print('未传递 Axis 参数。 在删除之前输入数组会被展开。')
print(np.delete(a,5))
print('\n')
print('删除每一行中的第二列：')
print(np.delete(a,1,axis = 1))
print('\n')


第一个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


未传递 Axis 参数。 在删除之前输入数组会被展开。
[ 0  1  2  3  4  6  7  8  9 10 11]


删除每一行中的第二列：
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]




## 数组去重

In [18]:
# numpy.unique 函数用于去除数组中的重复元素。
'''
arr：输入数组，如果不是一维数组则会展开
return_index：如果为 true，返回新列表元素在旧列表中的位置（下标），并以列表形式储
return_inverse：如果为 true，返回旧列表元素在新列表中的位置（下标），并以列表形式储
return_counts：如果为 true，返回去重数组中的元素在原数组中的出现次数
'''
import numpy as np
a = np.array([5,2,6,2,7,5,6,8,2,9])
print ('第一个数组：')
print (a)
print ('\n')
print ('第一个数组的去重值：')
u = np.unique(a)
print (u)
print ('\n')
print ('去重数组的索引数组：')
u,indices = np.unique(a, return_index = True)
print (indices)
print ('\n')
print ('我们可以看到每个和原数组下标对应的数值：')
print (a)
print ('去重数组的下标：')
u,indices = np.unique(a,return_inverse = True)
print (u)
print (indices)
print ('\n')
print ('返回去重元素的重复数量：')
u,indices = np.unique(a,return_counts = True)
print (u)
print (indices)
print ('\n')

第一个数组：
[5 2 6 2 7 5 6 8 2 9]


第一个数组的去重值：
[2 5 6 7 8 9]


去重数组的索引数组：
[1 0 2 4 7 9]


我们可以看到每个和原数组下标对应的数值：
[5 2 6 2 7 5 6 8 2 9]
去重数组的下标：
[2 5 6 7 8 9]
[1 0 2 0 3 1 2 4 0 5]


返回去重元素的重复数量：
[2 5 6 7 8 9]
[3 2 2 1 1 1]




# numpy的计算(数学函数)

In [19]:
import numpy as np
score = np.array([[80,88],[82,81],[75,81]])# 1. 获取所有数据最大值
result = np.max(score)
print(result)# 2. 获取某一个轴上的数据最大值
result = np.max(score,axis=0)
print(result)# 3. 获取最小值
result = np.min(score)
print(result)# 4. 获取某一个轴上的数据最小值
result = np.min(score,axis=0)
print(result)# 5. 数据的比较
result = np.maximum( [-2, -1, 0, 1, 2], 0 )
# 第一个参数中的每一个数与第二个参数比较返回大的
print(result)
result = np.minimum( [-2, -1, 0, 1, 2], 0 )
# 第一个参数中的每一个数与第二个参数比较返回小的
print(result)
result = np.maximum( [-2, -1, 0, 1, 2], [1, 2, 3, 4, 5] )
print(result)# 接受的两个参数，也可以大小一致;第二个参数只是一个单独的值时，其实是用到了维度的广播机制；
# 6. 求平均值
result = np.mean(score)
# 获取所有数据的平均值
print(result)
result = np.mean(score,axis=0)
# 获取某一行或者某一列的平均值
print(result)# 7. 求前缀和
arr = np.array([[1,2,3], [4,5,6]])
print(arr)
print(arr.cumsum(0))
'''
[1, 2, 3]------> |1 |2 |3 |
[4, 5, 6]------> |5=1+4 |7=2+5 |9=3+6|
'''
print(arr.cumsum(1))
'''
[1, 2, 3]------> |1 |2+1 |3+2+1 |
[4, 5, 6]------> |4 |4+5 |4+5+6 |
'''
# 8. argmin 求最小值索引
result = np.argmin(score,axis=0)
res=np.min(score,axis=0)
#这样我们就可以知道最小的 81 是第二排的，是从前往后遍历的
print(result,res)
# 9. 求每一列的标准差（这里是总体标准差）
# 标准差是一组数据平均值分散程度的一种度量。一个较大的标准差，代表大部分数值和其平均值之间差异较大；
# 一个较小的标准差，代表这些数据较接近平均值反应出数据的波动稳定情况，越大表示波动越大，越不稳定。
result = np.std(score,axis=0)
print(result)
# 10. 极 值
result = np.ptp(score,axis=None)#就是最大值和最小值的差
print(result)
# 拓展：方差 var, 协方差 cov, 计算平均值 average, 计算中位数 median
'''通用函数：
numpy.sqrt(array) 平方根函数
numpy.exp(array) e^array[i]的数组
numpy.abs/fabs(array) 计算绝对值
numpy.square(array) 计算各元素的平方 等于 array 2
numpy.log/log10/log2(array) 计算各元素的各种对数
numpy.sign(array) 计算各元素正负号
numpy.isnan(array) 计算各元素是否为 NaN
numpy.isinf(array) 计算各元素是否为 NaN
numpy.cos/cosh/sin/sinh/tan/tanh(array) 三角函数
numpy.modf(array) 将 array 中值得整数和小数分离，作两个数组返回
numpy.ceil(array) 向上取整,也就是取比这个数大的整数
numpy.floor(array) 向下取整,也就是取比这个数小的整数
numpy.rint(array) 四舍五入
numpy.trunc(array) 向 0 取整
numpy.cos(array) 正弦值
numpy.sin(array) 余弦值
numpy.tan(array) 正切值
numpy.add(array1,array2) 元素级加法
numpy.subtract(array1,array2) 元素级减法
numpy.multiply(array1,array2) 元素级乘法
numpy.divide(array1,array2) 元素级除法 array1./array2
numpy.power(array1,array2) 元素级指数 array1.^array2
numpy.maximum/minimum(array1,aray2) 元素级最大值
numpy.fmax/fmin(array1,array2) 元素级最大值，忽略 NaN
numpy.mod(array1,array2) 元素级求模
numpy.copysign(array1,array2) 将第二个数组中值得符号复制给第一个数组中值
numpy.greater/greater_equal/less/less_equal/equal/not_equal (array1,array2)
元素级比较运算，产生布尔数组
numpy.logical_end/logical_or/logic_xor(array1,array2)元素级的真值逻辑运算
'''

88
[82 88]
75
[75 81]
[0 0 0 1 2]
[-2 -1  0  0  0]
[1 2 3 4 5]
81.16666666666667
[79.         83.33333333]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [5 7 9]]
[[ 1  3  6]
 [ 4  9 15]]
[2 1] [75 81]
[2.94392029 3.29983165]
13


'通用函数：\nnumpy.sqrt(array) 平方根函数\nnumpy.exp(array) e^array[i]的数组\nnumpy.abs/fabs(array) 计算绝对值\nnumpy.square(array) 计算各元素的平方 等于 array 2\nnumpy.log/log10/log2(array) 计算各元素的各种对数\nnumpy.sign(array) 计算各元素正负号\nnumpy.isnan(array) 计算各元素是否为 NaN\nnumpy.isinf(array) 计算各元素是否为 NaN\nnumpy.cos/cosh/sin/sinh/tan/tanh(array) 三角函数\nnumpy.modf(array) 将 array 中值得整数和小数分离，作两个数组返回\nnumpy.ceil(array) 向上取整,也就是取比这个数大的整数\nnumpy.floor(array) 向下取整,也就是取比这个数小的整数\nnumpy.rint(array) 四舍五入\nnumpy.trunc(array) 向 0 取整\nnumpy.cos(array) 正弦值\nnumpy.sin(array) 余弦值\nnumpy.tan(array) 正切值\nnumpy.add(array1,array2) 元素级加法\nnumpy.subtract(array1,array2) 元素级减法\nnumpy.multiply(array1,array2) 元素级乘法\nnumpy.divide(array1,array2) 元素级除法 array1./array2\nnumpy.power(array1,array2) 元素级指数 array1.^array2\nnumpy.maximum/minimum(array1,aray2) 元素级最大值\nnumpy.fmax/fmin(array1,array2) 元素级最大值，忽略 NaN\nnumpy.mod(array1,array2) 元素级求模\nnumpy.copysign(array1,array2) 将第二个数组中值得符号复制给第一个数组中值\nnumpy.greater/greater_equal/less/less_equal/equal/not_equal (array1

# 数组的拼接与分割

## 数组的拼接

In [20]:
# 有的时候我们需要将两个数据加起来一起研究分析，我们就可以将其进行拼接然后分析
import numpy as np# 1. 根据轴连接的数组序列
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
# 要求 a,b 两个数组的维度相同
# print ('沿轴 0 连接两个数组：')
print (np.concatenate((a,b),axis= 0))
print ('\n')
print ('沿轴 1 连接两个数组：')
print (np.concatenate((a,b),axis = 1))
# 2. 根据轴进行堆叠
print ('沿轴 0 连接两个数组：')
print (np.stack((a,b),axis= 0))
print ('\n')
print ('沿轴 1 连接两个数组：')
print (np.stack((a,b),axis = 1))
# 3. 矩阵垂直拼接
v1 = [[0,1,2,3,4,5],
[6,7,8,9,10,11]]
v2 = [[12,13,14,15,16,17],
[18,19,20,21,22,23]]
result = np.vstack((v1,v2))
print(result)
# 4. 矩阵水平拼接
v1 = [[0,1,2,3,4,5],
[6,7,8,9,10,11]]
v2 = [[12,13,14,15,16,17],
[18,19,20,21,22,23]]
result = np.hstack((v1,v2))
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


沿轴 1 连接两个数组：
[[1 2 5 6]
 [3 4 7 8]]
沿轴 0 连接两个数组：
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


沿轴 1 连接两个数组：
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5 12 13 14 15 16 17]
 [ 6  7  8  9 10 11 18 19 20 21 22 23]]


# 数组的分割

In [21]:
# 1. 将一个数组分割为多个子数组
'''
参数说明：
ary：被分割的数组
indices_or_sections：是一个整数，就用该数平均切分，如果是一个数组，为沿轴切分的位置
（左开右闭）
axis：沿着哪个维度进行切向，默认为 0，横向切分。为 1 时，纵向切分
'''
import numpy as np
arr = np.arange(9).reshape(3,3)
print ('将数组分为三个大小相等的子数组：')
b = np.split(arr,3)
print (b)
# 2.numpy.hsplit 函数用于水平分割数组，通过指定要返回的相同形状的数组数量来拆分原数组。
harr = np.floor(10*np.random.random((2, 6)))
print ('原 array：')
print(harr)
print ('拆分后：')
print(np.hsplit(harr, 3))
# 3.numpy.vsplit 沿着垂直轴分割
a = np.arange(16).reshape(4,4)
print ('第一个数组：')
print (a)
print ('\n')
print ('竖直分割：')
b = np.vsplit(a,2)
print (b)

将数组分为三个大小相等的子数组：
[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]
原 array：
[[3. 6. 0. 2. 3. 3.]
 [5. 8. 9. 7. 2. 9.]]
拆分后：
[array([[3., 6.],
       [5., 8.]]), array([[0., 2.],
       [9., 7.]]), array([[3., 3.],
       [2., 9.]])]
第一个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


竖直分割：
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


# 数组中的nan和inf

In [22]:
'''
C 语言中表示最大的正整数值是 0x7FFF FFFF，最小的负整数是 0x8000 0000。
查阅资料后，发现 inf 表示无穷大，需要使用 float(‘inf’) 函数来转化，那么对应的就有
float('-inf') 表示无穷小了。
这样你就可以使用任意数来判断和它的关系了。
那什么时候会出现 inf 呢？ 比如一个数字除以 0，Python 中会报错，但是 numpy 中会是一个
inf
或者-inf
另外还有 nan，这种写法在 pandans 中常见，表示缺失的数据，所以一般用 nan 来表示。
任何与其做运算结果都是 nan（比如零除以零，在 numpy 中）
'''
import numpy as np# 创建一个 nan 和 inf #
a = np.nan
b = np.inf
print(a,type(a))
print(b,type(b))
# --判断数组中为 nan 的个数
t = np.arange(24,dtype=float).reshape(4,6)
# 将三行四列的数改成 nan
t[3,4] = np.nan
# 可以使用 np.count_nonzero() 来判断非零的个数
print(np.count_nonzero(t))# 并 且 np.nan != np.nan 结果 是 TRUE
# 所以我们可以使用这两个结合使用判断 nan 的个数
print(np.count_nonzero(t != t))
# 将 nan 替换为 0
t[np.isnan(t)] = 0
print(t)
# ----------练习： 处理数组中 nan
t = np.arange(24).reshape(4,6).astype('float')#
# 将数组中的一部分替换 nan
t[1,3:] = np.nan
print(t)
print('-------------------')
# 遍历每一列，然后判断每一列是否有 nan
for i in range(t.shape[1]):#获取当前列数据
    temp_col = t[:,i]
    # 判断当前列的数据中是否含有 nan
    nan_num = np.count_nonzero(temp_col != temp_col)# 条件成立说明含有 nan
    if nan_num != 0:
        # 将这一列不为 nan 的数据拿出来
        temp_col_not_nan = temp_col[temp_col == temp_col]# 将 nan 替换成这一列的平均值
        temp_col[np.isnan( temp_col )] = np.mean( temp_col_not_nan )
print(t)

nan <class 'float'>
inf <class 'float'>
23
1
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21.  0. 23.]]
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. nan nan nan]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
-------------------
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. 13. 14. 15.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]


# 二维数组的转置、轴滚动

In [2]:
#对换数组的维度
import numpy as np
a = np.arange(12).reshape(3,4)
print ('原数组：')
print (a )
print ('\n')
print ('对换数组：')
print (np.transpose(a))
# 与 transpose 一致
a = np.arange(12).reshape(3,4)
print ('原数组：')
print (a)
print ('\n')
print ('转置数组：')
print (a.T)
# 函数用于交换数组的两个轴
t1 = np.arange(24).reshape(4,6)
re = t1.swapaxes(1,0)
print (' 原 数 组 ：')
print (t1)
print ('\n')
print ('调用 swapaxes 函数后的数组：')
print (re)

原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


对换数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


转置数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
 原 数 组 ：
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


调用 swapaxes 函数后的数组：
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]
