# 一维数组

In [30]:
import numpy as np
list1 = [1,2,3,4]
oneArray = np.array(list1)
print(type(oneArray))
print(oneArray)
# 创建数组的多种形式
# 1. 直接传入列表的方式
t1 = np.array([1,2,3])
print(t1)
print(type(t1))
'''
[1 2 3]
<class 'numpy.ndarray'>
'''
# 2. 传入range生成序列
t2 = np.array(range(10))
print(t2)
print(type(t2))
'''
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
'''
# 3. 使用numpy自带的np.arange()生成数组
t3 = np.arange(0,10,2)
print(t3)
print(type(t3))
'''
[0 2 4 6 8]
<class 'numpy.ndarray'>
'''

<class 'numpy.ndarray'>
[1 2 3 4]
[1 2 3]
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[0 2 4 6 8]
<class 'numpy.ndarray'>


"\n[0 2 4 6 8]\n<class 'numpy.ndarray'>\n"

# ndarray与Python原生list运算效率对比

In [31]:
import random
import time
import numpy as np
a = []
for i in range(100000000):
    a.append(random.random())
t1 = time.time()
sum1 = sum(a)
t2 = time.time()
b = np.array(a)
t4 = time.time()
sum3 = np.sum(b)
t5 = time.time()
print(t2 - t1, t5 - t4)

0.3879826068878174 0.05917525291442871


# 创建二维数组

In [32]:
import numpy as np
list2 = [[1,2],[3,4],[5,6]]
twoArray = np.array(list2)
print(twoArray)

[[1 2]
 [3 4]
 [5 6]]


# 常用属性

In [33]:
list2 = [[1,2],[3,4],[5,6]]
twoArray = np.array(list2)
# 获取数组的维度( 注意： 与函数的参数很像)
print(twoArray.ndim)
# 形状（行，列）
print(twoArray.shape)
# 有多少个元素
print(twoArray.size)

2
(3, 2)
6


# 调整数组的形状

In [34]:
four = np.array([[1,2,3],[4,5,6]])
# 修改的是原有的
four.shape = (3,2)
print(four)
# 返回一个新的数组
four = four.reshape(3,2)
print(four)
# 将多维变成一维数组
five = four.reshape((6,),order='F')
# 默认情况下‘C’以行为主的顺序展开，‘F’（Fortran风格）意味着以列的顺序展开
six = four.flatten(order='F')
print(five)
print(six)
# 拓展：数组的形状
t = np.arange(24)
print(t)
print(t.shape)
# 转换成二维
t1 = t.reshape((4,6))
print(t1)
print(t1.shape)

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[1 3 5 2 4 6]
[1 3 5 2 4 6]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)


# Numpy的数据类型

In [35]:
import random
# 返回数组中每个元素的字节单位长度，dtype设置数据类型
f = np.array([1,2,3,4,5], dtype = np.int16)
print(f.itemsize) # 1 np.int8(一个字节)
# 获取数据类型
print(f.dtype)
# 调整数据类型
f1 = f.astype(np.int64)
print(f1.dtype)
# 拓展随机生成小数
# 使用python语法，保留两位
print(round(random.random(),2))
arr = np.array([random.random() for i in range(10)])
# 取小数点后两位
print(np.round(arr,2))

2
int16
int64
0.72
[0.05 0.39 0.87 0.2  0.5  0.24 0.33 0.08 0.73 0.4 ]


# 数组和数的计算

In [36]:
# 由于numpy的广播机制，在运算过程中，加减乘除的值被广播到所有的元素上面
t1 =np.arange(24).reshape((6,4))
print(t1+2)
print("-"*20)
print(t1*2)
print("-"*20)
print(t1/2)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
--------------------
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]
--------------------
[[ 0.   0.5  1.   1.5]
 [ 2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5]
 [10.  10.5 11.  11.5]]


# 数组与数组之间的操作

In [37]:
# 同种形状的数组(对应位置进行计算操作)
t1 = np.arange(24).reshape((6,4))
t2 = np.arange(100,124).reshape((6,4))
print(t1+t2)
print(t1*t2)
# 不同形状的多维数组不能计算
# t1 = np.arange(24).reshape((4,6))
# t2 = np.arange(18).reshape((3,6))
# print(t1)
# print(t2)
# print(t1-t2)
'''
ValueError: operands could not be broadcast together with shapes (4,6) (3,6)
'''

[[100 102 104 106]
 [108 110 112 114]
 [116 118 120 122]
 [124 126 128 130]
 [132 134 136 138]
 [140 142 144 146]]
[[   0  101  204  309]
 [ 416  525  636  749]
 [ 864  981 1100 1221]
 [1344 1469 1596 1725]
 [1856 1989 2124 2261]
 [2400 2541 2684 2829]]


'\nValueError: operands could not be broadcast together with shapes (4,6) (3,6)\n'

## 行数或者列数相同的一维数组和多维数组可以进行计算：
行形状相同(会与每一行数组的对应位相操作)

In [38]:
t1 = np.arange(24).reshape((4,6))
t2 = np.arange(0,6)
print(t1-t2)

[[ 0  0  0  0  0  0]
 [ 6  6  6  6  6  6]
 [12 12 12 12 12 12]
 [18 18 18 18 18 18]]


列形状相同(会与每一个相同维度的数组的对应位相操作)

In [39]:
t1 = np.arange(24).reshape((4,6))
t2 = np.arange(4).reshape((4,1))
print(t1-t2)

[[ 0  1  2  3  4  5]
 [ 5  6  7  8  9 10]
 [10 11 12 13 14 15]
 [15 16 17 18 19 20]]


# 数组中的轴

In [40]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(np.sum(a,axis=0)) # [5 7 9]
print(np.sum(a,axis = 1)) # [ 6 15]
print(np.sum(a))
a=np.arange(27).reshape((3,3,3))
print(a)
b=np.sum(a, axis=0)
print("-"*20)
print(b)
c=np.sum(a, axis=1)
print("-"*20)
print(c)
d=np.sum(a, axis=2)
print("-"*20)
print(d)
# 总结： 在计算的时候可以想象成是每一个坐标轴，分别计算这个轴上面的每一个刻度上的值，或者在二维数组中记住0表示列1表示行

[5 7 9]
[ 6 15]
21
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
--------------------
[[27 30 33]
 [36 39 42]
 [45 48 51]]
--------------------
[[ 9 12 15]
 [36 39 42]
 [63 66 69]]
--------------------
[[ 3 12 21]
 [30 39 48]
 [57 66 75]]


In [41]:
a = np.arange(24).reshape((2,3,4))
b = np.sum(a, axis=0)
print('-' * 20) 
print(b.shape)
c = np.sum(a, axis=1)
print('-' * 20) 
print(c.shape)
d = np.sum(a, axis=2)
print('-' * 20) 
print(d.shape)

--------------------
(3, 4)
--------------------
(2, 4)
--------------------
(2, 3)


# 索引和切片

In [42]:
import numpy as np

a = np.arange(10)
# 冒号分割切片参数start:stop:step来进行操作print(a[2:8:2]) # 从索引2到索引8，每隔2个取一个

# 如果只放置一个参数，如[2]，将返回与该索引相对应的单个元素
print(a[2],a)

# 如果为[2:]，表示从该索引开始以后的所有项都将被提取
print(a[2:])

print(a[2:8:2]) # 切片是左闭右开

2 [0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2 4 6]


In [43]:
# 多维数组的操作方法
import numpy as np
t1 = np.arange(24).reshape(4,6)
print(t1)
print('*'*20)
print(t1[1]) # 取一行(一行代表是一条数据，索引也是从0开始的) print(t1[1,:]) # 取一行
print('*'*20)
print(t1[1:])# 取连续的多行
print('*'*20)
print(t1[1:3,:])# 取连续的多行
print('*'*20)
print(t1[[0,2,3]])# 取不连续的多行
print('*'*20)
print(t1[[0,2,3],:])# 取不连续的多行
print('*'*20)
print(t1[:,1])# 取一列
print('*'*20)
print(t1[:,1:])# 连续的多列
print('*'*20)
print(t1[:,[0,2,3]])# 取不连续的多列
print('*'*20)
print(t1[2,3])# # 取某一个值,三行四列
print('*'*20)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[ 6  7  8  9 10 11]
********************
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
********************
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[ 1  7 13 19]
********************
[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [13 14 15 16 17]
 [19 20 21 22 23]]
********************
[[ 0  2  3]
 [ 6  8  9]
 [12 14 15]
 [18 20 21]]
********************
15
********************


# 数组中的数值修改

In [44]:
import numpy as np
t = np.arange( 24 ).reshape( 4, 6 )
# # 修改某一行的值
t[1, :] = 0
# # 修改某一列的值
t[:, 1] = 0
#
# # 修改连续多行
t[1:3, :] = 0#
# # 修改连续多列
t[:, 1:4] = 0#
# # 修改多行多列，取第二行到第四行，第三列到第五列
# t[1:4,2:5]=0
#
# # 修改多个不相邻的点
# t[[0,1],[0,3]]=0
# print(t)
# 可以根据条件修改，比如讲小于 10 的值改掉
t[t < 10] = 0# print(t)
# 使用逻辑判断
# np.logical_and & # np.logical_or |
# np.logical_not ~
t[(t > 2) & (t < 6)] = 0
# 与
t[(t < 2) | (t > 6)] = 0
# 或
t[~(t > 6)] = 0
# 非
# print(t)
t=t.clip(10,18)
print(t)
# # 拓 展
# # 三目运算（ np.where(condition, x, y)满足条件(condition)，输出 x，不满足输出y。)）
score = np.array( [[80, 88], [82, 81], [75, 81]] )
result = np.where( score > 80, True, False )
print( result )

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]
[[False  True]
 [ True  True]
 [False  True]]


# 数组的添加、删除和去重

## 数组的添加

In [ ]:
# 1. numpy.append 函数在数组的末尾添加值。 追加操作会分配整个数组，并把原来的数组复制到新数组中。
# 此外，输入数组的维度必须匹配否则将生成 ValueError。
'''
参 数 说 明 ：
arr： 输 入 数 组
values：要向 arr 添加的值，需要和 arr 形状相同（除了要添加的轴）
axis：默认为 None。当 axis 无定义时，是横向加成，返回总是为一维数组！当 axis 有定义的
时候，分别为 0 和 1 的时候。当
axis 有定义的时候，分别为 0 和 1 的时候（列数要相同）。当 axis 为 1 时，数组是加在右边
（行数要相同）。
'''
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print('第一个数组：')
print(a)
print('\n')
print(' 向 数 组 添 加 元 素 ：')
print(np.append(a, [7, 8, 9]))
print('\n')
print('沿轴 0 添加元素：')
print(np.append(a, [[7, 8, 9]], axis=0))
print('\n')
print('沿轴 1 添加元素：')
print(np.append(a, [[5, 5, 5], [7, 8, 9]], axis=1))
# 2. numpy.insert
# 函数在给定索引之前，沿给定轴在输入数组中插入值。# 如果值的类型转换为要插入，则它与输入数组不同。
# 插入没有原地的，函数会返回一个新数组。 此外，如果未提供轴，则输入数组会被展开。
a = np.array([[1, 2], [3, 4], [5, 6]])
print('第一个数组：')
print(a)
print('\n')
print('未传递 Axis 参数。 在插入之前输入数组会被展开。')
print(np.insert(a, 3, [11, 12]))
print('\n')
print('传递了 Axis 参数。 会广播值数组来配输入数组。')
print('沿轴 0 广播：')
print(np.insert(a, 1, [11], axis=0))
print('\n')
print('沿轴 1 广播：')
print(np.insert(a, 1, 11, axis=1))

## 数组中的删除

In [ ]:
#numpy.delete 函数返回从输入数组中删除指定子数组的新数组。 与 insert() 函数的情况一样，
# 如果未提供轴参数， 则输入数组将展开。
'''
参 数 说 明 ： arr： 输 入 数 组
obj：可以被切片，整数或者整数数组，表明要从输入数组删除的子数组 axis：
沿着它删除给定子数组的轴，如果未提供，则输入数组会被展开'''
import numpy as np
a = np.arange(12).reshape(3,4)
print('第一个数组：')
print(a)
print('\n')
print('未传递 Axis 参数。 在删除之前输入数组会被展开。')
print(np.delete(a,5))
print('\n')
print('删除每一行中的第二列：')
print(np.delete(a,1,axis = 1))
print('\n')


## 数组去重

In [ ]:
# numpy.unique 函数用于去除数组中的重复元素。
'''
arr：输入数组，如果不是一维数组则会展开
return_index：如果为 true，返回新列表元素在旧列表中的位置（下标），并以列表形式储
return_inverse：如果为 true，返回旧列表元素在新列表中的位置（下标），并以列表形式储
return_counts：如果为 true，返回去重数组中的元素在原数组中的出现次数
'''
import numpy as np
a = np.array([5,2,6,2,7,5,6,8,2,9])
print ('第一个数组：')
print (a)
print ('\n')
print ('第一个数组的去重值：')
u = np.unique(a)
print (u)
print ('\n')
print ('去重数组的索引数组：')
u,indices = np.unique(a, return_index = True)
print (indices)
print ('\n')
print ('我们可以看到每个和原数组下标对应的数值：')
print (a)
print ('去重数组的下标：')
u,indices = np.unique(a,return_inverse = True)
print (u)
print (indices)
print ('\n')
print ('返回去重元素的重复数量：')
u,indices = np.unique(a,return_counts = True)
print (u)
print (indices)
print ('\n')